export const faq_data = [
  {
    id: 1,
    question: "I want to help a homeless person I pass on the streets every day, or who is sleeping in front of my home",
    answer_html: "<p>Unless you feel that the situation is unsafe, ask the person if he or she needs assistance and has visited an organization that helps homeless people. You can let them know that <a href='https://www.coloradocoalition.org/'>https://www.coloradocoalition.org/community-resources-and-path)</a> will help them find more permanent housing, healthcare, and guidance.</p><p>If you are not comfortable engaging the person, then call 311 to let the city know that there is a homeless person who appears to need services, and they will send an outreach team. You should be able to let them know where the person is, what he or she is wearing, what condition he or she seems to be in, and whether it is an emergency.</p>",
    image: "https://images.unsplash.com/photo-1523847027398-d3eb27914c67?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3900&q=80",
  },
  {
    id: 2,
    question: "I see a homeless person who looks like he or she might be suffering from the cold, heat or other extreme weather",
    answer_html: "<p>Unless you feel unsafe doing so, ask if the person is ok, has someplace to go and needs help. The NYC Department of Homeless Services has Code Blue and Code Red procedures in place to ensure that homeless people have access to emergency shelter in extreme weather. You can call 311 to let the City know that there is a person in need of such emergency shelter (Note: When the temperature or wind chill is forecast to fall below 32 degrees, the call might be re-routed to 911). If the person seems to require medical attention, dial 911.</p>",
    image: "https://images.unsplash.com/photo-1456834292851-cd2d74fb491e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2989&q=80",
  },
  {
    id: 3,
    question: "I've called 311 about a homeless person, or told that person about the Colorado Coalition, but I still see the same person on the street every day",
    answer_html: "<p>Some homeless people have had bad experiences in the shelter system and are afraid, or prefer not, to return. Others have been wrongly denied shelter, even though they have a legal right to shelter. You can refer that person to the Colorado Coalition’s PATH profram, which can help. He or she should go to 2100 Broadway Denver, CO 80205. If you can, offer the person bus fare to get to the Coalition.</p>",
    image: "https://images.unsplash.com/photo-1526168637801-e9f490d6bc04?ixlib=rb-1.2.1&auto=format&fit=crop&w=2166&q=80",
  },
  {
    id: 4,
    question: "I see a homeless parent and child who seem to need help",
    answer_html: "<p>Parents with children should never have to sleep on the streets or in public places. If you see a parent with kids who seem to need help, you can approach and ask if they have a place to stay or need the address of a shelter intake facility. You can also dial 311, or tell them to visit the Coalitions Family Housing Support Center(<a href='https://www.coloradocoalition.org/family-support-services'>https://www.coloradocoalition.org/family-support-services</a>).</p>",
    image: "https://images.unsplash.com/photo-1517545084371-4a575dde2a02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1234&q=80",
  },
  {
    id: 5,
    question: "I think one of my child’s classmates is homeless, and I want to help without offending or embarrassing them",
    answer_html: "<p>It is extremely important to treat such issues with extreme confidentiality, given the stigma attached to homelessness among children. The best thing to do would be to contact the teacher or other appropriate person at the school and let him or her know of your concerns.</p>",
    image: "https://images.unsplash.com/photo-1529390079861-591de354faf5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
  },
  {
    id: 6,
    question: "Someone on the train or on the street asks me for money or food",
    answer_html: "<p>Each of us must make our own decisions about whom to help and how, and just because someone is asking for food or money doesn’t necessarily mean he or she is homeless. But it’s safe to assume that person would not be asking for help if help was not needed. If you do not feel comfortable handing someone money or food, you can direct them to a soup kitchen nearby <a href='https://www.foodbankrockies.org/find-food/'><https://www.foodbackrockies.org/find-food'</a></p>",
    image: "https://images.unsplash.com/photo-1502818364365-08cda033fee1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3290&q=80",
  },
  {
    id: 7,
    question: "I see a homeless person on the street who is severely inebriated or acting erratically and talking to themselves",
    answer_html: "<p>Call 311, unless the person clearly seems to be in need of emergency medical care, in which case call 911.</p>",
    image: "https://images.unsplash.com/photo-1566805972780-0f6fbefd137b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
  },
  {
    id: 8,
    question: "I see a homeless person who the police seem to be harassing or wrongly engaging",
    answer_html: "<p>Without becoming intrusive, try to get a badge number while taking notes on what is transpiring. Your mere presence as a witness may be helpful. Contact a homeless resource near you with a description of what you have seen.</p>",
    image: "https://images.unsplash.com/photo-1453873531674-2151bcd01707?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3650&q=80",
  },
  {
    id: 9,
    question: " I see a homeless person who is being harassed or attacked by strangers",
    answer_html: "<p>Dial 911 immediately.</p>",
    image: "https://images.unsplash.com/photo-1542367787-4baf35f3037d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
  },
  {
    id: 10,
    question: "I see a homeless person being denied service or being asked to leave a store or restaurant by police or others",
    answer_html: "<p>Politely ask the store or restaurant manager what the reason is for denying service or ejecting the homeless person, and let him or her know that even those without homes have the same rights as everyone else. If you are comfortable, offer to buy some coffee or food for the person being ejected.</p>",
    image: "https://images.unsplash.com/photo-1558709340-98600d57d931?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2698&q=80",
  },
  {
    id: 11,
    question: "I see a homeless person being told to leave a subway, park or other public place by police or others",
    answer_html: "<p>Without becoming intrusive, try to get a badge number while taking notes on what is transpiring. Your mere presence as a witness may be helpful. Contact a homeless resource near you with a description of what you have seen.</p>",
    image: "https://images.unsplash.com/photo-1522479764535-46d1a39bdd28?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
  },
  {
    id: 12,
    question: "I see a homeless person collecting bottles from the trash",
    answer_html: "<p>Many people rely on the income from bringing recyclables to redemption centers for their survival. Bringing in recyclables is good for the city, and it allows the homeless person to earn some money. You can offer them your own recyclables to help.</p>",
    image: "https://images.unsplash.com/photo-1535375743084-67f559ec192f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
  },
  {
    id: 13,
    question: "I would like to be able to give homeless people useful information about where to get help",
    answer_html: "<p>Give them the number of our chat bot, or the link to this website to connect them with more resources (they can visit this website using libraries free resources). Offering the person some spare change, an RTD pass or a gift card to a fast food restaurant along with the resource information is always appreciated.</p>",
    image: "https://images.unsplash.com/photo-1531090041372-c47fb16b796f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
  },
];
